apiVersion: argoproj.io/v1alpha1 # for versions before 1.9.0 use apps/v1beta2
kind: Rollout
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 1